import type { AppliedStatusEffectSpec } from '../types'

/** Where an ability is contextually relevant in combat.
 *  - 'attack' : ONLY appears in the attacker panel (boosts/enables attacks, damage mods).
 *  - 'defense': ONLY appears in the defender panel (DEF buffs, evasion, damage mitigation).
 *  - 'general': appears in both attack AND defense panels (combat-applicable utility).
 *  - 'utility': non-combat — only surfaces in the freeform Dice Roller, never in AttackModal
 *               (informational queries, exploration, social, crafting). */
export type CombatRole = 'attack' | 'defense' | 'general' | 'utility'

export interface ClassAbility {
  name: string
  sdCost: number
  hpCostAlt?: number     // Evoker abilities cost "1 SD OR X HP" — set this for them
  description: string
  tier: 'level1' | 'levelUp'  // level1 = starting abilities; levelUp = choose on level-up
  requiresRoll?: boolean  // true if the ability says "Roll to succeed"
  /** @deprecated Use combatRoles. Kept for legacy data. */
  combatRole?: CombatRole
  /** Where this ability surfaces. Strict filtering — see Ability.combatRoles for semantics.
   *  Defaults to ['utility'] if both fields omitted. */
  combatRoles?: CombatRole[]
  /** Status effects this ability auto-applies on commit. */
  appliedEffects?: AppliedStatusEffectSpec[]
}

export const CLASS_ABILITIES: Record<string, ClassAbility[]> = {
  Warrior: [
    // Level 1
    {
      name: 'Precision Strike',
      sdCost: 1,
      description: 'Once per scene, you can spend 1 SD instead of rolling to attack, guaranteeing a successful hit.',
      tier: 'level1',
      combatRole: 'attack',
    },
    {
      name: 'Fortified Defense',
      sdCost: 2,
      description: 'You can spend 2 SD to increase your DEF by 2 for a scene.',
      tier: 'level1',
      combatRole: 'defense',
    },
    {
      name: 'Relentless Assault',
      sdCost: 1,
      description: 'Immediately after an attack, successful or failed, you can spend 1 SD to attack again.',
      tier: 'level1',
      combatRole: 'attack',
    },
    // Level Up
    {
      name: 'Chosen Weapon',
      sdCost: 1,
      description: 'After a rest, choose a specific weapon type (sword, axe, bow, etc.). When using this weapon, you can spend 1 SD to enhance your attacks with 1d4 damage. This effect lasts until your next rest.',
      tier: 'levelUp',
      combatRole: 'attack',
    },
    {
      name: 'Steel Will',
      sdCost: 1,
      description: 'Once per scene, you can spend 1 SD to shrug off a Status Effect that affects your mind or senses.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Perfect Guard',
      sdCost: 1,
      description: 'When you spend SD to increase your DEF, it also applies to one ally within Reach if you spend an additional SD.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Duelist',
      sdCost: 1,
      description: 'When you target a single foe, you can spend 1 SD to keep them focused on you for a round.',
      tier: 'levelUp',
      combatRoles: ['attack'],
    },
    {
      name: 'Battlefield Instinct',
      sdCost: 1,
      description: 'While facing a hostile creature, you can spend 1 SD to get a yes or no answer to one of these questions: Is this creature expecting reinforcements? Does this creature have a trick up their sleeve? Is this creature trying to escape?',
      tier: 'levelUp',
      combatRoles: ['utility'],
    },
    {
      name: 'Exploit Opening',
      sdCost: 1,
      description: 'When an ally hits a target, spend 1 SD to immediately follow up with an attack against that target as part of your ally\'s turn.',
      tier: 'levelUp',
      combatRole: 'attack',
    },
    {
      name: 'Situational Awareness',
      sdCost: 1,
      description: 'Spend 1 SD to ask the GM one of the following, and get a clear answer: What is the biggest threat right now? What enemy is vulnerable or exposed? How can I gain the advantage?',
      tier: 'levelUp',
      combatRoles: ['utility'],
    },
    {
      name: 'Anti-magic Strike',
      sdCost: 1,
      description: 'When you make an attack, spend 1 SD to ignore any enchantments your target has on their armor.',
      tier: 'levelUp',
      combatRole: 'attack',
    },
    {
      name: 'Warrior\'s Eye',
      sdCost: 1,
      description: 'When you observe an enemy\'s weapon or fighting style, you may spend 1 SD to learn their maximum damage and if their weapon is enchanted or has any special traits.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
  ],

  Hunter: [
    // Level 1
    {
      name: 'Perceive Mind',
      sdCost: 1,
      description: 'Spend 1 SD to read a creature\'s body language, gaining insight into its mental state, intentions, or to understand if it is being deceptive or truthful. Roll to succeed. 10+ For the scene, you gain clear insight concerning the creature. 7-9 For the scene, you have vague insight concerning the creature. 2-6 You have no insight concerning the creature.',
      tier: 'level1',
      combatRole: 'utility',
      requiresRoll: true,
    },
    {
      name: 'Ambush',
      sdCost: 1,
      description: 'If you make a successful attack while unseen or hidden from your target, you can spend 1 SD to ignore the target\'s DEF.',
      tier: 'level1',
      combatRole: 'attack',
    },
    {
      name: 'Predator',
      sdCost: 1,
      description: 'Spend 1 SD to mark a single creature you can see. Until your next rest, you gain +1 damage against it, and you can always detect its trail.',
      tier: 'level1',
      combatRole: 'attack',
    },
    // Level Up
    {
      name: 'Uncanny Focus',
      sdCost: 1,
      description: 'Spend 1 SD to sharpen one of your physical senses to an almost superhuman level: sight, hearing, touch, smell, or taste. For the rest of the scene, when you focus on that sense, you can perceive information that would be imperceivable by most (for example: reading lips across a room, understanding conversations through a wall, detecting the smell of poison in a drink).',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Threat Assessment',
      sdCost: 1,
      description: 'Spend 1 SD to detect any non-magical danger in your area. These can be natural hazards, traps, or dangerous creatures. Roll to succeed. 10+ You are aware of all non-magical dangers in your area and how to avoid them for the rest of the scene. 7-9 For the rest of the scene, you become aware of some non-magical dangers, but not all, or are unaware of how to avoid them. 2-6 You remain unaware of the dangers in your area.',
      tier: 'levelUp',
      combatRole: 'utility',
      requiresRoll: true,
    },
    {
      name: 'Quick Reflexes',
      sdCost: 1,
      description: 'Spend 1 SD to react with inhuman speed, such as dodging a trap, evading an attack, or catching a falling object.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Wisdom of the Prey',
      sdCost: 1,
      description: 'Spend 1 SD to become instantly aware if any creature is trying to hide from, sneak, or track you, and know whether it\'s intelligent or animal. You do not know where the creature is.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'No Escape',
      sdCost: 1,
      description: 'When a creature attempts to flee from you, you may spend 1 SD to quickly catch up to them. Roll to succeed. 10+ You catch up to the creature with no issue. 7-9 You catch up to the creature, but there is an unexpected complication. 2-6 The creature evades you.',
      tier: 'levelUp',
      combatRoles: ['attack'],
      requiresRoll: true,
    },
    {
      name: 'Sense the Unnatural',
      sdCost: 1,
      description: 'Spend 1 SD to attune your senses to detect Magical, Undead, Aberrant, Elemental, or Construct creatures within Far range. You know the category and general direction of each, even through barriers, but not precise details.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Pathfinder',
      sdCost: 1,
      description: 'Spend 1 SD to find a way through a single, localized terrain obstacle that would normally be impassable without risk, such as a cliff, ravine, or sheer wall. This ability cannot be used to traverse large regions or extended hazards. Creatures guided by you must also spend 1 SD to follow.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Camouflage',
      sdCost: 1,
      description: 'You can spend 1 SD to blend into your surroundings for a scene, unless you attack, move, or speak.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Hunter\'s Mask',
      sdCost: 1,
      description: 'When attempting to appear as another humanoid creature, spend 1 SD to create a perfect disguise, including mannerisms and voice. This lasts until your next rest.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
  ],

  Vindicator: [
    // Level 1
    {
      name: 'Cause',
      sdCost: 1,
      description: 'Spend 1 SD, binding yourself to your chosen Cause until your next rest (choose one): Protect the helpless; Serve the master; Conquer the enemy; Crush the unworthy; Uphold the order. When you attempt an action that clearly aligns with your Cause, you gain +1 to the roll.',
      tier: 'level1',
      combatRole: 'utility',
    },
    {
      name: 'Leadership',
      sdCost: 1,
      description: 'Spend 1 SD to grant +1 to you and your allies\' action rolls for a scene, as long as they can see you.',
      tier: 'level1',
      combatRoles: ['attack', 'defense'],
    },
    {
      name: 'Strengthen',
      sdCost: 1,
      description: 'Spend 1 SD to increase your and your allies\' maximum damage by 2. For each creature affected, this lasts until they make a successful attack or the next rest.',
      tier: 'level1',
      combatRole: 'attack',
    },
    // Level Up
    {
      name: 'Vindictive Presence',
      sdCost: 1,
      description: 'Spend 1 SD to intimidate enemies engaging you in combat. For the rest of the scene, as long as they can see you, they will try to move farther away from you. They may still make ranged attacks against you.',
      tier: 'levelUp',
      combatRoles: ['defense'],
    },
    {
      name: 'Stand Strong',
      sdCost: 1,
      description: 'Allies within sight gain +1 DEF as long as you are actively fighting. Costs 1 SD.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Inspiration',
      sdCost: 1,
      description: 'When you hit with an attack, you may spend 1 SD to inspire a nearby ally. That ally regains 1 spent SD.',
      tier: 'levelUp',
      combatRoles: ['attack'],
    },
    {
      name: 'Vengeful Smite',
      sdCost: 1,
      description: 'When you strike an enemy who has harmed an ally, you may spend 1 SD to deal double damage.',
      tier: 'levelUp',
      combatRole: 'attack',
    },
    {
      name: 'Incur the Wrath',
      sdCost: 1,
      description: 'When an ally drops to 0 HP as a result of an attack, you may spend 1 SD to immediately make a strike against the attacker, if they are within range. If it hits, deal maximum damage.',
      tier: 'levelUp',
      combatRole: 'attack',
    },
    {
      name: 'War Cry',
      sdCost: 1,
      description: 'During combat, spend 1 SD and let out a mighty shout. For the rest of the scene, allies who fight within Nearby range of you gain +1 to damage rolls and cannot be moved unwillingly.',
      tier: 'levelUp',
      combatRoles: ['attack'],
    },
    {
      name: 'Foil',
      sdCost: 1,
      description: 'Spend 1 SD to cause a creature you can see to falter as they attempt an action. Roll to succeed. 10+ Their attempt fails. 7-9 They partially succeed, but not to the extent they wished. 2-6 They succeed in their attempt, and you are at a disadvantage against them.',
      tier: 'levelUp',
      combatRoles: ['defense'],
      requiresRoll: true,
    },
    {
      name: 'Shrine',
      sdCost: 1,
      description: 'When you spend 1 SD to bind yourself to a Cause, you may build a shrine out of materials in your possession or use the symbol of your devotion and spend 2 SD to dedicate it to your Cause. Until your next rest, as long as the shrine remains standing, you have the Clarity effect. If you act against your Cause, the effect ends.',
      tier: 'levelUp',
      combatRole: 'utility',
      appliedEffects: [{ effectName: 'Clarity', target: 'self', durationType: 'until-rest' }],
    },
    {
      name: 'Dedicated Weapon',
      sdCost: 1,
      description: 'Spend 1 SD to dedicate your weapon to your Cause until your next rest. Enemies who take damage from that weapon have their DEF reduced by -1. This applies once to each creature you deal damage to.',
      tier: 'levelUp',
      combatRole: 'attack',
    },
  ],

  Enchanter: [
    // Level 1
    {
      name: 'Runemaster',
      sdCost: 1,
      description: 'You can etch magical Runes onto objects using Lapis Lazuli. Each Rune uses 1 Lapis Lazuli. You can then activate the Runes to temporarily apply enchantments or curses from your Tome to those objects if you can see them, but only one enchantment or curse can be applied to a Rune at a time. Activating a Rune costs 1 SD. Runes remain active for the duration of a scene or until deactivated.',
      tier: 'level1',
      combatRole: 'utility',
    },
    {
      name: 'Magic Circle',
      sdCost: 3,
      description: 'You can spend 3 SD and use 5 Lapis Lazuli to etch an enchantment or curse you know in a circle on the ground that can fit up to five Medium creatures inside. Smaller circles can be etched as well. The circle lasts for a day, and the area within is affected by the enchantment or curse.',
      tier: 'level1',
      combatRole: 'utility',
    },
    {
      name: 'Reveal Enchantments',
      sdCost: 1,
      description: 'You can spend 1 SD to detect and identify any active enchantments or curses within Nearby range, even if they\'re hidden.',
      tier: 'level1',
      combatRole: 'utility',
    },
    // Level Up
    {
      name: 'Runic Chain',
      sdCost: 1,
      description: 'When you activate a Rune, you may spend 1 additional SD to have the enchantment or curse affect an additional item within Nearby range of the first, even if that item has no Rune.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Magical Bomb',
      sdCost: 2,
      description: 'When activating a Rune, spend 2 SD instead of 1 to overcharge it, causing an explosion that damages nearby creatures except the item holder. This can be done as part of the item holder\'s attack, adding your damage die to the damage. Roll to determine if the item is damaged: 10+ The item suffers no damage. 7-9 The item needs repair, but remains mostly functional. 2-6 The item is no longer functional and needs extensive repair.',
      tier: 'levelUp',
      combatRole: 'attack',
      requiresRoll: true,
    },
    {
      name: 'Runeskin',
      sdCost: 2,
      description: 'You may spend 2 SD to tattoo a Rune permanently onto your skin. When this Rune is activated, you take 1d4 damage.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Disenchant',
      sdCost: 1,
      description: 'Spend 1 SD to attempt to deactivate an enchantment or curse you are aware of. Roll to succeed: 10+ You succeed. 7-9 The targeted enchantment or curse is weakened, but remains. 2-6 Your attempt fails and the targeted enchantment or curse flares with a burst of extra potency for one scene.',
      tier: 'levelUp',
      combatRoles: ['attack', 'defense'],
      requiresRoll: true,
    },
    {
      name: 'Triggered Rune',
      sdCost: 1,
      description: 'When inscribing a Rune, you may spend 1 additional SD to bind it to a specific trigger condition. The Rune activates automatically when the condition is met with an enchantment or curse from your Tome. You must describe the trigger clearly when the Rune is inscribed. Once set, the trigger condition cannot be changed.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Incantation',
      sdCost: 1,
      description: 'Spend 1 SD to recite an enchantment or curse from your Tome, targeting yourself or a creature or object you can see. The effect is instantaneous and fades immediately.',
      tier: 'levelUp',
      combatRoles: ['attack', 'defense'],
    },
    {
      name: 'Runethief',
      sdCost: 1,
      description: 'If you can see a Rune you did not etch, you may spend 1 SD to try to gain control over it. Roll to succeed. 10+ The Rune becomes yours to control. 7-9 You gain a little control over the Rune, but it lasts for a few minutes. 2-6 You fail to control the Rune.',
      tier: 'levelUp',
      combatRoles: ['utility'],
      requiresRoll: true,
    },
    {
      name: 'Sign of Binding',
      sdCost: 2,
      description: 'When creating an enchantment or curse in your Tome, you may add the Sign of Binding. This sign allows the effect to persist on its target until it is removed magically (for example, by a Potion of Restoration or another enchantment). If an enchantment or curse containing the Sign of Binding is activated through a Rune or through Incantation, it costs 2 SD instead of 1.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Sign of Mind',
      sdCost: 2,
      description: 'When creating an enchantment or curse in your Tome, you may add the Sign of Mind. This sign allows the effect to influence or alter the mind of a creature it targets. If an enchantment or curse containing the Sign of Mind is activated through a Rune or through Incantation, it costs 2 SD instead of 1.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
  ],

  Delver: [
    // Level 1
    {
      name: 'Signs of Rites',
      sdCost: 1,
      description: 'Spend 1 SD to study your surroundings for traces of ancient Rites. If present, you determine where it resides and what its purpose was meant to be.',
      tier: 'level1',
      combatRole: 'utility',
    },
    {
      name: 'Ancient Rite',
      sdCost: 1,
      description: 'Spend 1 SD to trigger the power of a relic or ruin you touch that contains an ancient Rite. If the effect is ongoing, it remains active for one scene.',
      tier: 'level1',
      combatRole: 'utility',
    },
    {
      name: 'Quick Reflexes',
      sdCost: 1,
      description: 'Once per rest, you may spend 1 SD to use an Evasion you\'ve already used.',
      tier: 'level1',
      combatRole: 'defense',
    },
    // Level Up
    {
      name: 'Ritual of Appeasing',
      sdCost: 1,
      description: 'Spend 1 SD to conduct a ritual that calms or satisfies an active hazardous Rite in the area. The ritual takes a few minutes to perform. Until your next rest, that Rite will not target anyone involved in the ritual. You must describe the ritual and everyone involved must offer something of genuine value (to the GM\'s satisfaction) as sacrifice. The item or offering is permanently lost.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Dispel',
      sdCost: 1,
      description: 'Spend 1 SD to negate the effect of an ancient Rite in your area you are aware of. Roll to succeed. 10+ The Rite dissipates. 7-9 The Rite weakens or fades away for one round. 2-6 The Rite resists and flares up, possibly altering its behavior. The GM describes how.',
      tier: 'levelUp',
      combatRoles: ['attack', 'defense'],
      requiresRoll: true,
    },
    {
      name: 'Avoid',
      sdCost: 1,
      description: 'Spend 1 SD to pass safely through the vicinity of a hazardous Rite you are aware of. This allows you to bypass the effect once, and only applies to you.',
      tier: 'levelUp',
      combatRoles: ['defense'],
    },
    {
      name: 'Clean Getaway',
      sdCost: 1,
      description: 'Spend 1 SD. Any creature pursuing you and any creature traveling with you through non-magical means immediately loses the trail.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Mind Map',
      sdCost: 1,
      description: 'Spend 1 SD to imagine a map of your location. Until your next rest, you always know where you are, where the cardinal directions are, and cannot become lost.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Decipher Language',
      sdCost: 1,
      description: 'Spend 1 SD to study a written language during a focused scene. Roll to succeed. 10+ You fully learn to read, write, and speak the language fluently. Record it for future use. 7-9 You grasp general ideas, basic terms, and can communicate in broken form. Record it for future use, but note it as incomplete. 2-6 You misunderstand the language. Attempts to communicate cause confusion, and attempts to understand lead to misinterpretation.',
      tier: 'levelUp',
      combatRole: 'utility',
      requiresRoll: true,
    },
    {
      name: 'Disarm',
      sdCost: 1,
      description: 'Spend 1 SD to permanently disarm a trap you have already identified or seen triggered. The trap is neutralized and will not activate again unless repaired or rearmed.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Studious',
      sdCost: 1,
      description: 'When examining an ancient relic, ruin, or artifact – magical or mundane – you may spend 1 SD to recall scholarly knowledge. You learn relevant history, design purpose, cultural significance, or original function, as determined by the GM.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Guide',
      sdCost: 1,
      description: 'Spend 1 SD while navigating a hazardous area to determine the safest visible path forward. You and those who are guided by you avoid environmental dangers along this path until it\'s disrupted or you reach an unseen area.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
  ],

  Wildspeaker: [
    // Level 1
    {
      name: 'Change Tether',
      sdCost: 1,
      description: 'Spend 1 SD to change an active Tether from one Primal Force to another.',
      tier: 'level1',
      combatRole: 'utility',
    },
    {
      name: 'Invoke Force',
      sdCost: 1,
      description: 'Spend 1 SD to make a simple request of a Tethered Force to affect a target or local area you can see - except for requests that directly harm a creature (doing so fails and breaks your Tether). Roll to succeed. 10+ Your request is granted. 7-9 Your request is granted, but in an indirect way with unintended consequences. 2-6 Your request is misunderstood, and something else happens instead.',
      tier: 'level1',
      combatRoles: ['general'],
      requiresRoll: true,
    },
    {
      name: 'Extend Tether',
      sdCost: 1,
      description: 'You can spend 1 SD to extend one of your active Tethers to a willing creature you can see. Their Tether lasts as long as yours is active. You can extend a Tether to one creature at a time. They cannot make a request of the Tethered Force, but the bonuses you gained from the Tether apply to them as well.',
      tier: 'level1',
      combatRole: 'utility',
    },
    // Level Up
    {
      name: 'Earthsight',
      sdCost: 1,
      description: 'While Tethered to Earth, you can spend 1 SD to sense the movement of creatures within Nearby range, even if they are invisible or obscured, through vibrations in the ground. Any creatures you have extended this Tether to can also spend 1 SD to use this ability. This lasts for one scene.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Deep Breather',
      sdCost: 1,
      description: 'While Tethered to Water, you can spend 1 SD to gain the Water Breathing effect for as long as you are submerged, up to the next rest. Any creatures you have extended this Tether to can also spend 1 SD to use this ability.',
      tier: 'levelUp',
      combatRole: 'utility',
      appliedEffects: [{ effectName: 'Water Breathing', target: 'self', durationType: 'until-rest' }],
    },
    {
      name: 'Frostblood',
      sdCost: 1,
      description: 'While Tethered to Ice, you can spend 1 SD to be immune to cold damage and move across icy terrain without penalty. Any creatures you have extended this Tether to can also spend 1 SD to use this ability. This lasts for one scene.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Embermarked',
      sdCost: 1,
      description: 'While Tethered to Fire, you can spend 1 SD and be immune to burning damage, and you radiate with heat. Any creatures you have extended this Tether to can also spend 1 SD to use this ability. This lasts for one scene.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Wind Guardian',
      sdCost: 1,
      description: 'While Tethered to Air, you can spend 1 SD to be shielded from all non-magic ranged attacks. Any creatures you have extended this Tether to can also spend 1 SD to use this ability. This lasts for one scene.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Regrowth',
      sdCost: 1,
      description: 'While Tethered to Plant-life, you can spend 1 SD to restore the most recent HP loss suffered by you and any creatures you have extended this Tether to.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Beast-Tongue',
      sdCost: 1,
      description: 'Spend 1 SD to speak with animals (non-sentient Natural creatures) fluently for one scene. Most will treat you as a trusted ally unless given reason not to. Roll to succeed. 10+ Your communication with the animal accomplishes what you wanted. 7-9 The animal understands you and is friendly, but doesn\'t seem interested. 2-6 The animal does not understand you and is frightened or becomes hostile.',
      tier: 'levelUp',
      combatRole: 'utility',
      requiresRoll: true,
    },
    {
      name: 'Wild Empath',
      sdCost: 1,
      description: 'You may spend 1 SD to calm an animal, redirect it, or cause it to adopt you or an ally as part of its group. This works even in moments of fear or aggression. Roll to succeed. 10+ The animal responds favorably to your actions. 7-9 The animal is unbothered by you, but is not interested in being friendly. 2-6 Your actions anger or frighten the animal.',
      tier: 'levelUp',
      combatRole: 'utility',
      requiresRoll: true,
    },
    {
      name: 'Beast Link',
      sdCost: 1,
      description: 'Spend 1 SD to bond with an animal you can see. You can give it simple commands and, at will, sense what it sees, hears, or smells. While sensing, you\'re unaware of your own surroundings. The bond ends after one scene or when the animal is no longer willing.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
  ],

  Evoker: [
    // Level 1 — all cost 1 SD or 5 HP
    {
      name: 'Summon Vex',
      sdCost: 1,
      hpCostAlt: 5,
      description: 'Spend 1 SD or 5 HP to summon up to four Vex: small, flying spirits that attack enemies. You can summon them in any available space within Nearby range. They can pass through walls and obstacles, and follow your commands. The Vex persist until destroyed (1 HP) or dismissed.',
      tier: 'level1',
      combatRoles: ['attack'],
    },
    {
      name: 'Summon Fangs',
      sdCost: 1,
      hpCostAlt: 5,
      description: 'Spend 1 SD or 5 HP to summon up to four Fangs: huge snapping maws that burst from solid surfaces. You can summon them in any available space within Nearby range. You may summon them in any formation as long as each one is attached to a solid surface. The Fangs cannot move but will obey your commands. They persist until dismissed or destroyed (1 HP).',
      tier: 'level1',
      combatRoles: ['attack'],
    },
    {
      name: 'Soul Transfer',
      sdCost: 0,
      description: 'You may transfer any amount of HP or SD from yourself to a creature you touch. This ability has no cost other than what you give, but it cannot reduce you to 0 HP.',
      tier: 'level1',
      combatRoles: ['attack', 'defense'],
    },
    // Level Up
    {
      name: 'Elsesight',
      sdCost: 1,
      hpCostAlt: 2,
      description: 'Spend 1 SD or 2 HP to see from the perspective of one of your summoned creatures. During this, you are blind. You must be in the same dimension as your creature.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Soul Weapon',
      sdCost: 1,
      hpCostAlt: 2,
      description: 'Spend 1 SD or 2 HP to ignite your weapon with Soul Fire for the rest of the scene. Strikes from this weapon ignore armor while ignited. If you reduce a creature to 0 HP with this weapon, you regain 1 SD and 5 HP.',
      tier: 'levelUp',
      combatRole: 'attack',
    },
    {
      name: 'Radiant Outpouring',
      sdCost: 1,
      hpCostAlt: 5,
      description: 'Spend 1 SD or 5 HP to heal up to three allies you can see for 2d4 HP each. You cannot heal yourself.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Soul Anchor',
      sdCost: 1,
      hpCostAlt: 5,
      description: 'Once per rest, you can spend 1 SD or 5 HP to anchor a creature (not including yourself) to your soul. For the rest of the scene, if they would drop to 0 HP, they instead drop to 1 HP and the anchor is consumed. Only one anchor can be active at a time.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Soulguard',
      sdCost: 1,
      hpCostAlt: 5,
      description: 'Spend 1 SD or 5 HP to nullify half of the damage dealt to an ally within Reach (rounded down).',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Mark of Passing',
      sdCost: 1,
      hpCostAlt: 5,
      description: 'Spend 1 SD or 5 HP to mark a creature you can see for death. Until the end of the scene, the next instance of damage they take is doubled and the mark fades. You may only have one marked creature at a time; marking a new one removes the previous mark.',
      tier: 'levelUp',
      combatRole: 'attack',
    },
    {
      name: 'Conjure Soul Fire',
      sdCost: 1,
      hpCostAlt: 5,
      description: 'Spend 1 SD or 5 HP to conjure a flickering tongue of Soul Fire in your hand. You may hurl it as a ranged attack (Far); this attack ignores DEF. You may also use the flame as a magical light source or to ignite flammable material. Soul Fire burns brighter when Undead creatures are Nearby.',
      tier: 'levelUp',
      combatRole: 'attack',
    },
    {
      name: 'Fear of the Grave',
      sdCost: 1,
      hpCostAlt: 5,
      description: 'Spend 1 SD or 5 HP to instill a creature you can see with the dread of death. Roll to succeed. 10+ The creature has the Fear effect for the rest of the scene: they will not willingly move closer to you, target you, or stay in melee range. 7–9 They flinch, hesitate, or back off briefly. 2-6 The creature resists the fear.',
      tier: 'levelUp',
      combatRoles: ['attack'],
      requiresRoll: true,
      appliedEffects: [{ effectName: 'Fear', target: 'target', durationType: 'scenes', remaining: 1, onSuccess: true }],
    },
    {
      name: 'Death\'s Memory',
      sdCost: 1,
      hpCostAlt: 5,
      description: 'Spend 1 SD or 5 HP to touch the corpse of a sentient creature and call its final moments into your mind. Roll to succeed. 10+ You clearly witness a memory or insight from the creature\'s death: what they saw, felt, or knew. You may ask the GM a specific question about their final moments to get a truthful answer, as long as the creature themselves knew the answer. 7-9 The memory is fragmented or emotionally overwhelming – you still learn something useful, but you are briefly stunned. 2-6 The memory lashes back and you gain the Cursed effect until your next rest.',
      tier: 'levelUp',
      combatRole: 'utility',
      requiresRoll: true,
    },
  ],

  Tecton: [
    // Level 1
    {
      name: 'Geometer\'s Sight',
      sdCost: 1,
      description: 'Spend 1 SD to study a structure or terrain. For the rest of the scene, you and your allies gain 1d4 to rolls for navigating that structure or terrain.',
      tier: 'level1',
      combatRole: 'utility',
    },
    {
      name: 'Seal of the Mind',
      sdCost: 1,
      description: 'Spend 1 SD to memorize any object. You can reproduce it flawlessly from memory later as long as you have the proper materials, although you cannot replicate any magical properties the original possessed.',
      tier: 'level1',
      combatRole: 'utility',
    },
    {
      name: 'The Returning Principle',
      sdCost: 1,
      description: 'When a creature within Reach strikes you, you may spend 1 SD to half the incoming damage and deal 1 damage back to the attacking creature.',
      tier: 'level1',
      combatRole: 'defense',
    },
    // Level Up
    {
      name: 'Unfolding Pattern',
      sdCost: 1,
      description: 'Spend 1 SD to predict the actions of everything you can currently see for the next few moments. Roll to succeed. 10+ The GM summarizes the exact actions of everything you can see for the next few moments, and you can react to change the events. 7-9 The GM provides a general idea of what is about to happen. 2-6 You don\'t know what is going to happen.',
      tier: 'levelUp',
      combatRoles: ['general'],
      requiresRoll: true,
    },
    {
      name: 'Doctrine of the Body',
      sdCost: 1,
      description: 'When studying a creature, spend 1 SD to learn its DEF, current HP, Tags, and damage die.',
      tier: 'levelUp',
      combatRoles: ['utility'],
    },
    {
      name: 'Counterpoise',
      sdCost: 1,
      description: 'Spend 1 SD to observe the flow of combat and adjust to the rhythm of each attack. For the rest of the scene, if attacked by a creature whose damage die is larger than yours, you temporarily gain its damage die.',
      tier: 'levelUp',
      combatRoles: ['attack', 'defense'],
    },
    {
      name: 'Discipline of the Body',
      sdCost: 1,
      description: 'Spend 1 SD to align your body and mind. For the next round, you become immune to all negative Status Effects. Any unwanted Status Effect currently afflicting you is removed.',
      tier: 'levelUp',
      combatRole: 'defense',
    },
    {
      name: 'Discordance',
      sdCost: 1,
      description: 'Spend 1 SD to use strikes or pressure points to disrupt a magical effect on an object or creature within Close range for the rest of the scene. This includes magically inflicted Status Effects, enchantments, and curses. Roll to succeed. 10+ The effect collapses harmlessly. 7–9 The effect is disrupted for one round. 2–6 You misjudge the effect\'s strength and take 1d4 damage from backlash. The effect persists.',
      tier: 'levelUp',
      combatRoles: ['attack', 'defense'],
      requiresRoll: true,
    },
    {
      name: 'Illumination',
      sdCost: 1,
      description: 'Spend 1 SD to align focus with another creature within Nearby range, sharing a unified clarity of thought and purpose. Skill Bonuses are doubled for you and this creature until the end of the scene.',
      tier: 'levelUp',
      combatRoles: ['attack', 'defense'],
    },
    {
      name: 'Fulcrum Strike',
      sdCost: 1,
      description: 'Spend 1 SD to meditate on the laws of force and motion. For the rest of the scene, your attacks ignore DEF.',
      tier: 'levelUp',
      combatRole: 'attack',
    },
    {
      name: 'Enlightenment',
      sdCost: 1,
      description: 'Once per rest, you may spend 1 SD to roll twice on any action roll and take the higher result.',
      tier: 'levelUp',
      combatRoles: ['attack', 'defense', 'general'],
    },
    {
      name: 'Work of Wonder',
      sdCost: 2,
      description: 'Once per rest, you may spend 2 SD to spend the scene creating a Work of Wonder. Using materials you possess, craft, build, or fabricate something that instills awe. This can be a work of art, an article of clothing, an intricate mechanism, or any other thing that captures your skill and knowledge. Friendly or neutral sentient creatures who see this creation become inspired by you, and you gain +3 to action rolls concerned with persuading, deceiving, or befriending them.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
  ],

  Alchemist: [
    // Level 1
    {
      name: 'Elixir',
      sdCost: 1,
      description: 'Spend 1 SD to combine up to three potions into a single elixir. All effects occur simultaneously when consumed. The elixir\'s duration matches the longest-lasting potion used in the mix.',
      tier: 'level1',
      combatRole: 'utility',
    },
    {
      name: 'Analyze Substance',
      sdCost: 1,
      description: 'Spend 1 SD to study a substance or object. You learn what Essences it contains (if any), and whether it has been altered by magic or poison.',
      tier: 'level1',
      combatRole: 'utility',
    },
    {
      name: 'Alchemical Bolt',
      sdCost: 1,
      description: 'Spend 1 SD to activate the Essences of a potion you designed in your hand. The reaction releases instantly as a ranged effect at a single target within Far range. The result matches the potion\'s usual effect but lasts only 1 round.',
      tier: 'level1',
      combatRole: 'attack',
    },
    // Level Up
    {
      name: 'Liminalis Gate',
      sdCost: 1,
      description: 'You can create a means of travel between two points in the same dimension. Anchor Circle: Once per rest, spend 1 SD to form a circle of 3 Essences of Element as an anchor circle on the ground. Only one may exist at a time. Creating a new one renders the previous inert. Portal Circle: Once per rest, spend 1 SD to form a circle of 3 Essences of Element to link instantly to the anchor circle. Once ignited with fire, the portal opens and remains open for one round, then collapses into ash. All creatures who pass through the portal before it collapses are teleported to the anchor circle instantly. If the anchor circle is obstructed, the creatures are teleported to an unoccupied space close to the anchor circle.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Scry',
      sdCost: 1,
      description: 'Spend 1 SD and 2 Essences of Sense. Spread the Essence over a mirror and gaze into its surface. You can see and hear a known creature for one scene. If the target creature is in the same dimension as you, the mirror faintly pulls toward their location, even across great distances. The effect lasts for one day.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Solar Lens',
      sdCost: 1,
      description: 'Coat a glass, crystal, or metal sphere with 1 Essence of Element and 1 Essence of Vitality and leave it in sunlight for an hour to charge it with solar energy. The charge is permanent until the sphere is destroyed. You can spend 1 SD to release a blinding beam from the sphere at a target within Far range. Roll to succeed. 10+ The target is Blinded for one scene. If Undead, it also ignites on fire for one round. 7–9 The target is Blinded for one round. 2–6 You or an ally is struck and Blinded for one round.',
      tier: 'levelUp',
      combatRole: 'attack',
      requiresRoll: true,
      appliedEffects: [{ effectName: 'Blindness', target: 'target', durationType: 'scenes', remaining: 1, onSuccess: true }],
    },
    {
      name: 'Homunculus Agent',
      sdCost: 1,
      description: 'Spend 1 SD, 1 Essence of Vitality, and 1 Essence of Transformation. Shape clay or scrap metal into a Small humanoid figure that awakens for one day. The Homunculus Agent has your HP but no DEF, and follows simple commands. It can carry and manipulate small objects. You may see and hear through its senses at will. It can repeat phrases or messages you tell it. After a day, it crumbles.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Elemental Mastery',
      sdCost: 1,
      description: 'Spend 1 SD and 1 Essence of Element to compel an Elemental creature you can see to follow one simple command for a scene. Roll to succeed: 10+ The Elemental obeys without resistance and acts to fulfill your command. 7–9 The Elemental obeys, but only briefly or imperfectly. It may twist your command or stop if harmed. 2–6 The Elemental resists and turns hostile toward you.',
      tier: 'levelUp',
      combatRoles: ['attack'],
      requiresRoll: true,
    },
    {
      name: 'Arcane Traces',
      sdCost: 1,
      description: 'Spend 1 SD and 1 Essence of Sense. Scatter the Essence into the air; it reacts visibly to lingering magic. You learn what kind of magical forces are active in the area and their relative strength, but not their exact effects.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
    {
      name: 'Seal of Karakat',
      sdCost: 1,
      description: 'Spend 1 SD, 1 Essence of Element, and 1 Essence of Decay to inscribe a circular barrier upon the ground. For one scene, the area inside becomes an anti-magic field: magical effects and enchanted items are suppressed, and Magical creatures within gain Fatigue. Breaking the circle ends the seal.',
      tier: 'levelUp',
      combatRoles: ['attack', 'defense'],
    },
    {
      name: 'Artegried\'s Abjuration',
      sdCost: 1,
      description: 'Spend 1 SD, and draw a line or circle of 1 Essence of Decay, 1 Essence of Transformation, and 1 Essence of Element upon the ground. Undead, Aberration, and Elemental creatures cannot cross the line for a scene. The line holds until your next rest or the line is dissolved with salt water.',
      tier: 'levelUp',
      combatRoles: ['defense'],
    },
    {
      name: 'Alchemical Bread',
      sdCost: 1,
      description: 'Spend 1 SD and 1 Essence of Vitality to transmute a small amount of dirt into three palm-sized loaves of dense, nourishing bread. Each loaf grants 2 temporary HP when eaten and crumbles after one day if uneaten.',
      tier: 'levelUp',
      combatRole: 'utility',
    },
  ],
}
